#!/usr/bin/env python3
"""
scripts/verify_setup.py
-----------------------
Pre-flight check: verifies that all required components are in place
before starting the FastAPI server.

Run from project root:
    python scripts/verify_setup.py

Exit code 0 = all checks passed.
Exit code 1 = one or more checks failed.
"""

import sys
from pathlib import Path

# ── Add backend/ to import path ───────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "backend"))

from config import settings

PASS = "  [OK] "
FAIL = "  [FAIL]"
WARN = "  [WARN]"

failures: list[str] = []


def check(condition: bool, pass_msg: str, fail_msg: str, warn_only: bool = False) -> bool:
    if condition:
        print(f"{PASS} {pass_msg}")
        return True
    else:
        symbol = WARN if warn_only else FAIL
        print(f"{symbol} {fail_msg}")
        if not warn_only:
            failures.append(fail_msg)
        return False


def main() -> int:
    print("\n" + "=" * 60)
    print("  VisualFind — Setup Verification")
    print("=" * 60 + "\n")

    # ── 1. Python version ─────────────────────────────────────────────────────
    major, minor = sys.version_info[:2]
    check(
        major == 3 and minor >= 10,
        f"Python {major}.{minor} (3.10+ required)",
        f"Python {major}.{minor} is too old — requires 3.10+",
    )

    # ── 2. Required packages ──────────────────────────────────────────────────
    print()
    packages = {
        "fastapi":    "FastAPI web framework",
        "uvicorn":    "ASGI server",
        "PIL":        "Pillow image library",
        "numpy":      "NumPy",
        "faiss":      "FAISS similarity search",
        "pydantic":   "Pydantic data validation",
    }
    for pkg, label in packages.items():
        try:
            __import__(pkg)
            check(True, f"{label} installed", "")
        except ImportError:
            check(False, "", f"{label} ({pkg}) not installed — run: pip install -r backend/requirements.txt")

    # Optional: torch
    print()
    try:
        import torch
        check(True, f"PyTorch {torch.__version__} installed (embedding extraction available)", "")
    except ImportError:
        check(True, "PyTorch not installed — OK for API-only usage", "", warn_only=True)
        print(f"{WARN}   → Install with: pip install torch torchvision")

    # ── 3. Dataset directories ────────────────────────────────────────────────
    print()
    check(
        settings.images_dir.exists(),
        f"Images directory found: {settings.images_dir.relative_to(PROJECT_ROOT)}",
        f"Images directory missing: {settings.images_dir}\n"
        "     → Extract ut-zap50k-images.zip to project root",
    )
    check(
        settings.metadata_csv.exists(),
        f"Metadata CSV found: {settings.metadata_csv.relative_to(PROJECT_ROOT)}",
        f"Metadata CSV missing: {settings.metadata_csv}\n"
        "     → Extract ut-zap50k-data.zip to project root",
        warn_only=True,
    )

    # ── 4. FAISS index + catalog ──────────────────────────────────────────────
    print()
    index_path   = settings.data_dir / "index.faiss"
    catalog_path = settings.data_dir / "catalog.json"
    embeddings_path = settings.data_dir / "embeddings.npy"

    check(
        index_path.exists(),
        f"FAISS index found ({index_path.stat().st_size // 1024:,} KB)",
        "FAISS index not found — run: python backend/build_index.py",
    )
    check(
        catalog_path.exists(),
        f"Catalog JSON found",
        "Catalog JSON not found — run: python backend/build_index.py",
    )
    check(
        embeddings_path.exists(),
        "Embeddings .npy found",
        "Embeddings file not found (optional — will be regenerated by build_index.py)",
        warn_only=True,
    )

    # ── 5. Catalog entry count ────────────────────────────────────────────────
    if catalog_path.exists():
        import json
        with open(catalog_path) as f:
            catalog = json.load(f)
        print()
        check(
            len(catalog) > 0,
            f"Catalog contains {len(catalog):,} products",
            "Catalog is empty — re-run build_index.py",
        )

    # ── Summary ───────────────────────────────────────────────────────────────
    print()
    print("=" * 60)
    if failures:
        print(f"  [FAIL] {len(failures)} check(s) failed. Fix the issues above.")
        print("=" * 60 + "\n")
        return 1
    else:
        print("  [OK]  All required checks passed. Ready to start the server.")
        print("        -> python -m uvicorn main:app --reload --port 8000")
        print("=" * 60 + "\n")
        return 0


if __name__ == "__main__":
    sys.exit(main())
